### ISSUE TITLE
False Positive: FINISHED fuer FAILED

### ISSUE THREAD

**Issue by kba** [infolis/infoLink#32]
http://infolis.gesis.org/infolink/api/execution/611ac540-8df0-11e5-bf13-db6946410e6b sollte failed sein

**Comment by bolandka** [comment]
my 2 cents on FINISHED vs. FAILED for TextExtractor:
Sometimes pdfBox fails to extract text from pdfs (e.g. due to encoding issues). In this case, a suitable error message should be logged, the pdf file skipped and the algorithm continued for remaining input files. If the TextExtractor algorithm finishes orderly, its status should be FINISHED even if one or more pdf files could not be converted. 
If the algorithm encounters a fatal error which causes it to terminate prematurely (e.g. in case the input files cannot be found), its status should be FAILED.
I corrected the log levels (error instead of fatal when execution does not terminate prematurely), added more helpful log messages indicating a pdfBox error occurred and corrected the number of output files (which in this case should be 0 instead of 1).

**Comment by kba** [comment]
Makes sense. If the result of a TextExtractor is zero outputFiles, there is nothing to continue on. but I suppose it can be deduced from the number of outputFiles of the execution if the process should continue, if that number can be relied on now.
