### ISSUE TITLE
QueryService Instantiation

### ISSUE THREAD

**Issue by Dommii** [infolis/infoLink#34]
A query service can (currently) either be a HTMLQueryService or a SolrQueryService. The class QueryService itself is an abstract class. Within the test, I directly instantiated the subclass I needed. 
How can we now post a QueryService via the API such that the correct subclass is instantiated? Is this already possible and I just miss it?

**Comment by kba** [comment]
Add the subclasses to the data model and live with the redundancy? Why do we need to instantiate an anonymous subclass of the abstract class directly?

**Comment by bolandka** [comment]
In addition to that: what do you think about not demanding a uri for QueryService in the execution of algorithms using one but instead having the execution field specify which class to use? Then the service can be instantiated and posted inside that execution. This way, we can also specify this nicely in a json file (e.g. in a json file for calling ApplyPatternAndResolve add  "queryService":"SolrQueryService"). You can use the Registry (currently available in the support_tags branch only) to retrieve the class using the given class name.

**Comment by kba** [comment]
Some form of composition, like the relationship between `Execution` and `Algorithm` is necessary. If every query service were a proper class in the data model, then every algorithm would have to be as well. Plus there will be subclasses and specializations in the future.

However I don't completely grok the depdencies for resolving at the moment, so maybe there's complexity I'm overlooking.

As for using a Registry: I'm in favor of having an easier way to specify classes and better hide our implementation (c.f. algorithm names in the execution) but I'm hesitant because there were unforeseen problems in the past. Will it work with our serialisation? Is it smart enough to notice moved classes? Not against it, just a reminder that we should test that thoroughly.

**Comment by Dommii** [comment]
What I currently see as a problem by specifying a class for the QueryService in the execution is that we can have more than one QueryService when we want to query in more than one repository. Since we have to set the target and reliability for each QueryService, I'm not sure how to implement this in one execution, e,g, for "queryServices":"SolrQueryService, HTMLQueryService" where do we specify the targets and reliabilities?

**Comment by Dommii** [comment]
How about that: as suggested by Katarina, we specify the classes if the QueryServices in the exeuction, e.g. "queryServices":["SolrQueryService", "HTMLQueryService]" and the target, reliability are fixed. This way, nobody can define a new QueryService but that would anyway be very difficult since they are at the moment tailored to da|ra.

**Comment by kba** [comment]
Sounds reasonable.

Since these services are geared towards dara right now, maybe we could re-create subclasses of them with Dara somewhere in them and list those in the data model/API specs. Makes our intention clearer.

**Comment by kba** [comment]
Has been implemented #38
