### ISSUE TITLE
Nullpointer in the Resolver

### ISSUE THREAD

**Issue by Dommii** [infolis/infoLink#57]
ERROR [Fri Nov 20 22:13:26 CET 2015 -- Resolver] Execution threw an Exception: java.lang.NullPointerException

http://infolis.gesis.org/infolink/api/execution/297d0e30-8fcc-11e5-87d1-9febea864153

Maybe already solved by this commit?
https://github.com/infolis/infolis-web/commit/b690c1af38bdf925f5f82cd1bbe88d572c64e036

**Comment by kba** [comment]
Run it again and check the Tomcat log, that should indicate the actual location of the NPE

**Comment by zuphilip** [comment]
Isn't this related to #53? Maybe even to #42, if that is still open?

**Comment by kba** [comment]
```
java.lang.NullPointerException
        at io.github.infolis.algorithm.Resolver.execute(Resolver.java:391)
        at io.github.infolis.algorithm.BaseAlgorithm.run(BaseAlgorithm.java:183)
        at io.github.infolis.scheduler.ExecutionScheduler$1.run(ExecutionScheduler.java:60)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
```

The relevant snippet:

``` java
      }
        //determine the best search result for the textual reference
        SearchResult bestSearchResult = null;
        double bestConfidence = -1.0;
        log.debug("Selecting the best search results");
        for (SearchResult sr : resultValues.keySet()) {
            if (resultValues.get(sr) > bestConfidence) {
                bestConfidence = resultValues.get(sr);
                bestSearchResult = sr;
            }
        }
        //create and post the instance representing the search result
        Entity referencedInstance = new Entity();
        referencedInstance.setTags(getExecution().getTags());
        referencedInstance.setIdentifier(bestSearchResult.getIdentifier()); // <-- NPE happens here
        referencedInstance.setName(bestSearchResult.getTitles().get(0));
        referencedInstance.setNumber(bestSearchResult.getNumericInformation().get(0));
        getOutputDataStoreClient().post(Entity.class, referencedInstance)
```

**Comment by kba** [comment]
From what I gather, the problem happens when there are no results.

**Comment by kba** [comment]
> Isn't this related to #53? Maybe even to #42, if that is still open?

I think this is an actual bug, not related to file or data storage.

**Comment by bolandka** [comment]
Indeed, that's a clear error in the code. I'll push a fix. And write some more useful tests for the reference resolving part now...

**Comment by bolandka** [comment]
Found multiple sources for NPEs....

Normally, it should never be the case that bestSearchResult is null because the validate method makes sure that search results are given, the resultValues map always has at least one entry.
BUT:
1) its score may be NaN because of this confidenceValue computation:

```
confidenceValue += 1 - ((double) r.getListIndex() / (double) results.get(results.size() - 1).getListIndex());
```

`results` is the list of all search results given as input. See what happens when there's only one search result and it has list index 0... NaN is not greater than -1, so searchResult remains at null -> exception occurs at the location you marked. However, this is not what caused the exception in this case.

2) even if there is a bestSearchResult, there can still be a NPE:

```
referencedInstance.setNumber(bestSearchResult.getNumericInformation().get(0));
```

A searchResult may have an empty numericInformation field, simply when there are no digits included in the title. Which is a totally valid case, e.g.: "Arbeitsorientierung (ALLBUS) " is a dataset title in dara.

The second issue is was caused the NPE in your call.
