### ISSUE TITLE
no URIs for patterns

### ISSUE THREAD

**Issue by bolandka** [infolis/infoLink#8]
InfolisPattern instances are not assigned any URI yet - thus PatternApplier fails

**Comment by kba** [comment]
https://github.com/infolis/infoLink/blob/8b79757c5419f637d2251e839080176854d89b04/src/main/java/io/github/infolis/algorithm/FrequencyBasedBootstrapping.java#L148

**Comment by kba** [comment]
iterate patterns and client.post them in https://github.com/infolis/infoLink/blob/8b79757c5419f637d2251e839080176854d89b04/src/main/java/io/github/infolis/infolink/luceneIndexing/PatternInducer.java#L285

**Comment by kba** [comment]
Fixed, test works, but fails eventually with "JDWP exit error AGENT_ERROR_INVALID_EVENT_TYPE(204): ExceptionOccurred [eventHelper.c:834]
FATAL ERROR in native method: JDWP ExceptionOccurred, jvmtiError=AGENT_ERROR_INVALID_EVENT_TYPE(204)"

Could be due to Thread.stop() ? http://stackoverflow.com/questions/5539923/agent-error-invalid-event-type-when-testing-an-eclipse-plugin

**Comment by kba** [comment]
Replaced SafeMatching with a thread-safe alternative.

StudyContext had a reference to InfolisPattern. Needs a reference to a URI pointing to a InfolisPattern.
